### ISSUE TITLE
Some resources from earlier this year are missing

### ISSUE THREAD

**Issue by sneakernets** [fragglet/RomeroDoomDump#1]
Romero released full sprite rotations of enemies and a few extra development sprites on twitter and dropbox that did not show up in the April dump. Are those noteworthy of being uploaded to this repository? I haven't seen any mention of them.

**Comment by fragglet** [comment]
They're definitely worth adding.

**Comment by fragglet** [comment]
So it was actually from December (so not this year), and can be found here:

https://archive.org/details/DOOMART1993

Feel free to send a pull request, or alternatively I'll commit them myself later.

**Comment by fragglet** [comment]
Ah, doomart1993.zip doesn't include the extra rotations. Those were posted separately:

https://twitter.com/romero/status/543372859368689664
https://twitter.com/romero/status/543362629977124865

possessed.zip is still available on Dropbox but doomguy-all-rotations.zip wasn't. I managed to find what I believe is a copy of it: https://soulsphere.org/downloads/doomguy-all-rotations.zip

**Comment by sneakernets** [comment]
Yeah, it's strewn everywhere -- which is why I was concerned that we might lose those assets if we didn't do something about it. :cry:

**Comment by fragglet** [comment]
Me too, which is part of the reason for creating this repository.

**Comment by fragglet** [comment]
Fixed in becca1725b03ff9bcfba28a3ff641f85281b50ea.

**Comment by fragglet** [comment]
Also added the unreleased MIDIs, so this should be a fairly comprehensive collection now :)
